name: Deploy Korean Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll & Bundler
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to gh-pages root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: .
          publish_branch: gh-pages
          user_name: hyungseokkim
          user_email: khkhvv@gmail.com
